#!/bin/bash

function notebook() {
    local nb_folder="$1"
    for path in `ls "${nb_folder}/"*.jl`; do
        jupytext -s "${path}"
    done
    mv "${nb_folder}/"*.ipynb "book/notebooks"
}

$*
exit 0
