#!/bin/bash

function notebook() {
    local nb_folder="$1"
    local nb_paths=`ls "${nb_folder}"`
    for path in "${nb_paths}"; do
        jupytext -s "${nb_folder}/${path}"
    done
    mv "${nb_folder}/"*.ipynb "book/notebooks"
}

$*
exit 0
