# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: High Performance Machine Learning in Julia
author: Juan S. Lara
copyright: "2023"
logo: img/logo.png

parse:
  myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https] 
  myst_dmath_double_inline: true  

execute:
  execute_notebooks: off

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/juselara1/teoj.nvim
  branch: main 

html:
  use_issues_button: true
  use_repository_button: true
